clubs_response_id = {
    "type": "object",
    "properties": {
        "id": {"type": "integer"},
        "bookTitle": {"type": "string"},
        "bookAuthors": {"type": "string"},
        "publicationYear": {"type": "integer"},
        "description": {"type": "string"},
        "telegramChatLink": {"type": "string", "format": "uri"},
        "owner": {"type": "integer"},
        "members": {"type": "array", "items": {"type": "integer"}},
        "reviews": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer"},
                    "club": {"type": "integer"},
                    "user": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "integer"},
                            "username": {"type": "string"},
                        },
                        "required": ["id", "username"],
                    },
                    "review": {"type": "string"},
                    "assessment": {"type": "integer"},
                    "readPages": {"type": "integer"},
                    "created": {"type": "string", "format": "date-time"},
                    "modified": {"type": "null"},
                },
                "required": [
                    "id",
                    "club",
                    "user",
                    "review",
                    "assessment",
                    "readPages",
                    "created",
                    "modified",
                ],
            },
        },
        "created": {"type": "string", "format": "date-time"},
        "modified": {"type": "null"},
    },
    "required": [
        "id",
        "bookTitle",
        "bookAuthors",
        "publicationYear",
        "description",
        "telegramChatLink",
        "owner",
        "members",
        "reviews",
        "created",
        "modified",
    ],
    "$schema": "https://json-schema.org/draft/2020-12/schema",
}
